---
title: "Aplicação network analysis - gephi e igraph"
author: "Rômulo Damasceno"
date: "9/5/2021"
output: html_document
---

```{r setup, include=FALSE}

#install.packages(c("igraph","RColorBrewer"))

library(tidyverse)
library(igraph)
library(RColorBrewer)

```

### Importação

```{r}

# Casos e conexões (Nodes, Edges)
primary_school <- read_csv('C:/Users/romul/Desktop/Projetos R/network_analysis/network-analysis-aprendizado/network-analysis-practice/igraph/primaryschool.csv') 

# Nodos e características sociodemográficas  
metadata <- read_csv("C:/Users/romul/Desktop/Projetos R/network_analysis/network-analysis-aprendizado/network-analysis-practice/igraph/metadata_primaryschool.csv")
  
```

### Manipulação dos datasets

#### Criação de uma coluna com os pesos das interações para cada indivíduo. Peso = contagem do número de interações

```{r}

primary_school_freq <- primary_school %>%
  group_by(Source) %>% 
  count(Target) %>% 
  arrange(-n)
  
```

#### Criação de um objeto igraph, atribuição dos pesos

```{r}
# Studant contact
Stucont <- graph_from_data_frame(primary_school_freq,
                                 directed = FALSE,
                                 vertices = metadata)

# Atribuição dos pesos para os edges do grafo
E(Stucont)$weight <-E(Stucont)$n


# Detalhamento estrutural 

Stucont

# 242 8317 singificam número de nodes e edges
# UNW singifica undirected network, DNW directed network (W = edge weighted)
# attr = attributes, name, class, gender (vertex attributes),
      #  n e weight = edge attributes
```

### Data Exploration
